import { ArrowRight, BadgeCheck, CalendarCheck, Search, ShieldCheck, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import { services } from '../../data/services'
export default function Home(){ return <main>
<section className="bg-gradient-to-br from-msp-softGreen to-msp-softWarm"><div className="page-shell grid min-h-[660px] items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">MULTI-SERVICE PORTAL</p><h1 className="mt-5 font-display text-5xl font-bold leading-[1.05] text-msp-primary md:text-7xl">Trusted help for your <span className="text-msp-accent">everyday needs</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-msp-secondary">Discover verified electricians, plumbers, cleaners, carpenters and repair professionals. Browse approved providers freely, compare their experience and pricing, then log in only when you are ready to book.</p><div className="mt-8 flex flex-wrap gap-4"><Link to="/providers" className="btn-primary">Find providers <ArrowRight className="ml-2" size={18}/></Link><Link to="/services" className="btn-secondary">Explore services</Link></div></div><div className="card p-8 md:p-10"><p className="eyebrow">HOW MSP WORKS</p><div className="mt-7 space-y-5">{[[Search,'Search freely','Find approved providers by category, city, price and rating without an account.'],[BadgeCheck,'Choose confidently','Review provider details, skills, experience and pricing.'],[CalendarCheck,'Book and track','Create a booking and follow its status from your dashboard.']].map(([Icon,title,text])=><div key={title} className="flex gap-4 rounded-xl bg-msp-softGreen p-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-msp-accent"><Icon/></span><div><h3 className="font-bold text-msp-primary">{title}</h3><p className="mt-1 text-sm text-msp-secondary">{text}</p></div></div>)}</div></div></div></section>
<section id="services" className="page-shell"><p className="eyebrow">SERVICES</p><div className="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h2 className="display-title">Services provided by us</h2><p className="mt-3 text-msp-secondary">Professional assistance for homes, offices and local businesses.</p></div><Link to="/services" className="font-bold text-msp-accent">View all services →</Link></div><div className="mt-9 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.slice(0,6).map(({id,icon:Icon,title,description})=><article key={id} className="card p-6"><span className="grid h-12 w-12 place-items-center rounded-xl bg-msp-softGreen text-msp-accent"><Icon/></span><h3 className="mt-5 font-display text-xl font-bold text-msp-primary">{title}</h3><p className="mt-2 leading-6 text-msp-secondary">{description}</p></article>)}</div></section>
<section id="about" className="bg-msp-primary text-white"><div className="page-shell grid gap-10 lg:grid-cols-2"><div><p className="eyebrow !text-msp-lightAccent">ABOUT MSP</p><h2 className="mt-4 font-display text-4xl font-bold">A safer marketplace for customers and service professionals.</h2><p className="mt-5 leading-8 text-white/75">Providers complete profiles, skills and document verification before approval. Customers get a clear booking trail from request creation through completion.</p></div><div className="grid gap-4 sm:grid-cols-2">{[[ShieldCheck,'Verified ecosystem'],[Star,'Quality-focused'],[CalendarCheck,'Transparent bookings'],[BadgeCheck,'Role-based experience']].map(([Icon,text])=><div key={text} className="rounded-2xl border border-white/15 bg-white/5 p-5"><Icon className="text-msp-lightAccent"/><p className="mt-3 font-bold">{text}</p></div>)}</div></div></section>
<section id="contact" className="page-shell text-center"><p className="eyebrow">NEED HELP?</p><h2 className="mt-4 display-title">Let’s get your service request moving.</h2><p className="mx-auto mt-4 max-w-2xl text-msp-secondary">Create an account, complete your profile, and book trusted professionals through one connected platform.</p><div className="mt-7 flex justify-center gap-4"><Link to="/register" className="btn-primary">Create account</Link><Link to="/contact" className="btn-secondary">Contact us</Link></div></section>
</main> }
