import { zodResolver } from '@hookform/resolvers/zod'
import { useState } from 'react'
import { useForm } from 'react-hook-form'
import toast from 'react-hot-toast'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { z } from 'zod'
import useAuth from '../../hooks/useAuth'
import { getDashboardForRole } from '../../utils/roles'
const schema=z.object({email:z.string().email('Enter a valid email'),password:z.string().min(6,'Password must contain at least 6 characters')})
export default function Login(){const [serverError,setServerError]=useState(''); const {login}=useAuth(); const navigate=useNavigate(); const location=useLocation(); const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm({resolver:zodResolver(schema)}); const submit=async(values)=>{setServerError('');try{const auth=await login(values);toast.success('Welcome back');const requested=typeof location.state?.from === 'string' ? location.state.from : location.state?.from?.pathname;const destination=requested||getDashboardForRole(auth.role);const state=location.state?.bookingProvider ? {provider:location.state.bookingProvider} : undefined;navigate(destination,{replace:true,state})}catch(error){const message=error.response?.data?.message||'Invalid email or password';setServerError(message)}};return <AuthShell label="WELCOME BACK" title="Login to your account" intro="Log in to manage your bookings, find professionals and access your account."><form onSubmit={handleSubmit(submit)} className="space-y-5">{location.state?.message&&<p className="rounded-lg border border-msp-accent/20 bg-msp-softWarm p-3 text-sm font-semibold text-msp-secondary">{location.state.message}</p>}<Field label="Email address" error={errors.email?.message}><input className="field" type="email" placeholder="you@example.com" {...register('email')}/></Field><Field label="Password" error={errors.password?.message}><input className="field" type="password" placeholder="Enter your password" {...register('password')}/></Field>{serverError&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{serverError}</p>}<button disabled={isSubmitting} className="btn-primary w-full disabled:opacity-60">{isSubmitting?'Logging in...':'Log in'}</button></form><p className="mt-6 text-center text-sm text-msp-muted">Don&apos;t have an account? <Link className="font-bold text-msp-accent" to="/register">Create account</Link></p></AuthShell>}
function Field({label,error,children}){return <label className="block"><span className="mb-2 block text-sm font-bold text-msp-primary">{label}</span>{children}{error&&<span className="mt-1 block text-sm text-red-600">{error}</span>}</label>}
export function AuthShell({label,title,intro,children}){return <main className="bg-gradient-to-br from-msp-softGreen to-msp-softWarm px-[5%] py-16"><div className="mx-auto grid min-h-[620px] max-w-6xl items-center gap-12 lg:grid-cols-2"><section><p className="eyebrow">MULTI-SERVICE PROVIDER</p><h1 className="mt-5 font-display text-5xl font-bold leading-tight text-msp-primary">Welcome to <span className="text-msp-accent">MSP.</span></h1><p className="mt-5 max-w-xl text-lg leading-8 text-msp-secondary">{intro}</p><ul className="mt-8 space-y-3 font-semibold text-msp-secondary"><li>✓ Find verified providers</li><li>✓ Manage service bookings</li><li>✓ Access a secure role-based account</li></ul></section><section className="card p-7 md:p-10"><p className="eyebrow">{label}</p><h2 className="mt-3 font-display text-3xl font-bold text-msp-primary">{title}</h2><p className="mb-7 mt-2 text-msp-muted">Enter your details below to continue.</p>{children}</section></div></main>}
