import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import toast from 'react-hot-toast'
import { Link, useNavigate } from 'react-router-dom'
import { z } from 'zod'
import useAuth from '../../hooks/useAuth'
import { AuthShell } from './Login'
const schema=z.object({email:z.string().email('Enter a valid email'),role:z.enum(['CUSTOMER','PROVIDER']),password:z.string().min(6,'Password must contain at least 6 characters'),confirmPassword:z.string()}).refine(v=>v.password===v.confirmPassword,{message:'Passwords do not match',path:['confirmPassword']})
export default function Register(){const {register:registerUser}=useAuth();const navigate=useNavigate();const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm({resolver:zodResolver(schema),defaultValues:{role:'CUSTOMER'}});const submit=async({confirmPassword,...payload})=>{try{await registerUser(payload);toast.success('Account created. Please log in.');navigate('/login',{replace:true})}catch(error){toast.error(error.response?.data?.message||'Registration failed')}};return <AuthShell label="GET STARTED" title="Create your account" intro="Create an account to book reliable services or grow your business as a professional provider."><form onSubmit={handleSubmit(submit)} className="space-y-5"><Input label="Email" error={errors.email?.message}><input className="field" type="email" {...register('email')} placeholder="you@example.com"/></Input><Input label="Register as" error={errors.role?.message}><select className="field" {...register('role')}><option value="CUSTOMER">Customer</option><option value="PROVIDER">Service Provider</option></select></Input><div className="grid gap-4 sm:grid-cols-2"><Input label="Password" error={errors.password?.message}><input className="field" type="password" {...register('password')} placeholder="Create password"/></Input><Input label="Confirm password" error={errors.confirmPassword?.message}><input className="field" type="password" {...register('confirmPassword')} placeholder="Confirm password"/></Input></div><button disabled={isSubmitting} className="btn-primary w-full">{isSubmitting?'Creating account...':'Create account'}</button></form><p className="mt-6 text-center text-sm text-msp-muted">Already have an account? <Link className="font-bold text-msp-accent" to="/login">Log in</Link></p></AuthShell>}
function Input({label,error,children}){return <label className="block"><span className="mb-2 block text-sm font-bold text-msp-primary">{label}</span>{children}{error&&<span className="mt-1 block text-xs text-red-600">{error}</span>}</label>}
